name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Include this line if you have submodules

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build Project
        run: mvn clean install -f ./pom.xml

      - name: Run Tests
        run: mvn test -f ./pom.xml
